### ISSUE TITLE
Extensible cannot build on stackage-nightly

### ISSUE THREAD

**Issue by mihaimaruseac** [fumieval/extensible#12]
Even though it only depends on `freer-effects` for benchmarks, the build system on stackage-nightly doesn't allow it to build until `freer-effects` is also released.

**Comment by mihaimaruseac** [comment]
I was wrong, sorry.

**Comment by bergmark** [comment]
This is still an issue but only for building the benchmarks.

**Comment by fumieval** [comment]
Split off the benchmarks: https://github.com/fumieval/extensible-benchmarks
