### ISSUE TITLE
[question] Is it faster than MTL?

### ISSUE THREAD

**Issue by eckyputrady** [fumieval/extensible#15]
I read this [post](https://www.schoolofhaskell.com/user/fumieval/extensible/the-world-s-fastest-extensible-effects-framework) and the benchmark says that this is faster than MTL.

Is it true for every condition? Is there any condition where it will be slower? (e.g. deeper stack).

I am trying to learn Free / Freer but hesitate when I heard they are significantly slower than MTL.

**Comment by fumieval** [comment]
Well MTL is faster (the benchmark shows 794.5 _nano_ seconds while extensible is 9.752microseconds). 

https://www.reddit.com/r/haskell/comments/6o77oc/the_worlds_fastest_extensible_effects_framework/dkf8udh/

However another benchmark indicates that the asymptotic performance of `extensible` is better for deeply left-associative loop. Multiplying the loop by 10 times made mtl 17x slower but extensible is 11x.

`extensible` is the fastest implementation as far as I know, but in general monad transformers are much faster.

**Comment by eckyputrady** [comment]
Thanks for the clarification. Yeah, I did read the benchmark incorrectly. 🙂
