### ISSUE TITLE
Should catchEff remove an effect?

### ISSUE THREAD

**Issue by starper** [fumieval/extensible#16]
Maybe I'm wrong, or maybe it's not even possible, but it feels like `catchEff` should remove an effect, not introduce one.
[Here](https://pursuit.purescript.org/packages/purescript-run/1.0.0/docs/Run.Except#v:catch) is a similar `PureScript` library, which, I hope, will serve as an example of what I'm talking about.

**Comment by fumieval** [comment]
That makes sense to me. `catchEff` has this type in order to implement a [MonadError](https://hackage.haskell.org/package/mtl-2.2.1/docs/Control-Monad-Except.html#t:MonadError) instance.

Do you think `runEitherEff m >>= either handler return` deserves a new function?

**Comment by starper** [comment]
I think it does. I thought about writing my own `catchEff'` function using `runEitherEff m >>= either handler return`, but then I looked in the code and found that there is a difference between `catchEff` and `runEitherEff`. First one calls `compareMembership` and the second one calls `leadership`, so I thought that there is a reason for this and it wasn't completely obvious for me that using `runEitherEff` instead of `catchEff` won't break something.

**Comment by starper** [comment]
I guess, I'm doing something wrong, but I've just tried to compile this code
```haskell
data FileSystem r where
  ReadFile
    :: FilePath
    -> FileSystem (Either SomeException ByteString)

readFile
  :: forall xs
  .  Associate "fs" FileSystem xs
  => Associate "fs_error" (EitherEff SomeException) xs
  => FilePath
  -> Eff xs ByteString
readFile fp = liftEff #fs (ReadFile fp)
           >>= either (throwEff #fs_error) pure

foo
  :: forall xs
  .  Associate "fs" FileSystem xs
  => Eff xs (Either SomeException ByteString)
foo = runEitherEff @"fs_error" $ readFile "foo" -- "runEitherEff" here is something like to "try"
```
but got an error
```
Couldn't match type `Elaborate
                             "fs" (Data.Extensible.Internal.MapSuccKey (FindAssoc "fs" xs))'
                     with 'Expecting (n0 'Data.Extensible.Internal.:> FileSystem)
        arising from a use of readFile
      The type variable `n0' is ambiguous
```

**Comment by fumieval** [comment]
I think that is logically impossible. `readFile` doesn't know how to instantiate `#fs` after removing one effect , so you need to instantiate the effect set:

```haskell
foo :: forall xs. Associate "fs" FileSystem xs => Eff xs (Either SomeException ByteString)
foo = castEff (runEitherEff @ "fs_error" (readFile "foo")
  :: Eff '["fs" >: FileSystem] (Either SomeException ByteString))
```

**Comment by starper** [comment]
Does this mean that if I have `runEitherEff @ "fs_error" m` and `m` has not only `fs` but 5 or 10 other effects, then I have to specify them all in `Eff '["fs" >: FileSystem, ...] (Either SomeException ByteString)`? And will wrapping this in some `catchEff'` help?

**Comment by fumieval** [comment]
Yes, you'll need to instantiate those effects. And no, it would introduce a new type level operation and it would make typechecking significantly harder.

**Comment by fumieval** [comment]
Closing as wontfix; this kind of thing should be avoided.
