### ISSUE TITLE
Why not defined type family `(++)` of Record and Variant

### ISSUE THREAD

**Issue by matsubara0507** [fumieval/extensible#17]
type family [`(++)`](https://hackage.haskell.org/package/extensible-0.4.6/docs/Data-Extensible-Product.html#t:-43--43-) of type lebel list is defined in extensible.

But, undefined `(++)` for Record and Variant.
if defined one, We can write below code:

```Haskell
type A = Record '[ "aaa" >: Bool ]
type B = A ++ Record '[ "bbb" >: Bool ]
````
Of course, We can define `A` and` B` after defining the type of fields `type FieldA = '["aaa">: Bool] ` without one.
But, I think that it's more useful if `(++)` for Record is defined.

I think that it's easy to define using `PolyKInds`.

```Haskell
type family (++) (t1 :: a) (t2 :: a) :: a where
  '[] ++ ys = ys
  (x ': xs) ++ ys = x ': xs ++ ys
  (h :* xs) ++ (h :* ys) = h :* (xs ++ ys)
  (h :| xs) ++ (h :| ys) = h :| (xs ++ ys)
```

Can I create a PR ?

**Comment by fumieval** [comment]
I don't think so. `(++)` should be well-kinded.
