### ISSUE TITLE
[question] Aeson instance

### ISSUE THREAD

**Issue by winterland1989** [fumieval/extensible#4]
I have take the approach in 'examples/aeson.hs' to declare `Record`'s `FromJson/ToJson` instance in my own project, but orphan instance always bother me, and newtype wrappers are verbose,  is it possible to include `Record` and `Variant`'s instance for `FromJson/ToJson` in extensible itself?

**Comment by fumieval** [comment]
Good question -- the downside is that it would pull a large amount of dependencies. But that may be fine, lens used to depend on aeson for example.

I'll think it over.

**Comment by winterland1989** [comment]
Thanks for your consideration! BTW. extensible is really a nice library to work with ; )

**Comment by fumieval** [comment]
Shipped extensible-0.4.7.2 with aeson instances.
